# Site
name: "Military Investor"
title: "Investing Education Specifically for Military Members and Veterans"
description: "How to Invest: Military Edition"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: https://www.militaryinvestor.org
google_analytics: 'G-7CRPGVHDK5'
#disqus: 'militaryinvestor'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ken:
    name: Ken
    display_name: Ken
    gravatar: 88b9dcd6c5e59c7e1f10b78d9300db0b
    email: ken@militaryinvestor.org
    web: https://militaryinvestor.org
    twitter: https://twitter.com/MilitaryInvestr
    description: "Author of the Military Investor Blog and avid investing nerd."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-1134580594196826"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
