# Site
name: "MILITARY INVESTOR (Under Construction)"
title: "Investing Education Specifically for Military Members and Veterans"
description: "My original Wordpress-based website imploded. However, this outage has given me some time to re-assess the content I was providing, and I've decided to re-write my previous posts to make them easier to understand.  Expect that shiny, edited content will be available (hosted on Github) by the first of the year."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ken:
    name: Ken
    display_name: Ken
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    #email: ken@militaryinvestor.org
    web: https://militaryinvestor.org
    description: "Author of the Military Investor Blog and avid investing nerd."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
